#
# Homepod sensors
#
- platform: template
  # 传感器列表
  sensors:
    # 实体名称：小写，下划线
    kitchen_temperature:
      unique_id: "kitchen_temperature"  
      # （可选）传感器数值的单位
      unit_of_measurement: '℃'
      #（必须）定义一个获取传感器状态（数值）的模板
      value_template: '{{float}}'
    kitchen_humidity:
      unique_id: "kitchen_humidity"  
      # （可选）传感器数值的单位
      unit_of_measurement: '%'
      #（必须）定义一个获取传感器状态（数值）的模板
      value_template: '{{value}}'
   
 
        
        